#!/bin/sh

echo "$(whoami):x:$(id -u):$(id -g)::/:/bin/sh" > /tmp/fakepasswd
mkdir /tmp/cache > /dev/null 2>&1

docker run \
    -it \
    -v $(pwd):/home \
    -v /tmp/cache:/.cache \
    -v /tmp/fakepasswd:/etc/passwd \
    -u $(id -u):$(id -g) \
    seven_segment \
    west $@
#     --device /dev/ttyUSB0 \
#     --device /dev/ttyUSB1 \
