[target.thumbv6m-none-eabi]
rustflags = [
    "-C", "linker=arm-none-eabi-gcc",
    "-C", "link-arg=-Tlink.x",
    ]

[build]
target = "thumbv6m-none-eabi"
# target = "thumbv7m-none-eabi"
rustflags = [ "-C", "link-arg=-Tlink.x"]
